image: go1.2
script:
  - make test
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
publish:
  github:
    branch: update-makefile
    script: make deb
    artifacts:
      - deb/sphinx.deb
    tag: $(cat deb/sphinx/DEBIAN/control | grep Version | cut -d " " -f 2)
    token: {{github_token}}
    user: Clever
    repo: sphinx
